class VirtualKeyInfo:
    def __init__(self, vk_code, vk_name, vk_desc):
        self.vk_code = vk_code
        self.vk_name = vk_name
        self.vk_desc = vk_desc

g_vk_list = [
    VirtualKeyInfo(0x08, "BKSP", "백스페이스 키"),
    VirtualKeyInfo(0x09, "TAB", "Tab 키"),
    VirtualKeyInfo(0x0D, "RET", "Enter 키"),
    VirtualKeyInfo(0x14, "CAPS", "Caps Lock 키"),
    VirtualKeyInfo(0x1B, "ESC", "Esc 키"),
    VirtualKeyInfo(0x20, "SPACE", "스페이스바"),
    VirtualKeyInfo(0x21, "PGUP", "Page Up 키"),
    VirtualKeyInfo(0x22, "PGDN", "Page Down 키"),
    VirtualKeyInfo(0x23, "END", "End 키"),
    VirtualKeyInfo(0x24, "HOME", "Home 키"),
    VirtualKeyInfo(0x25, "LEFT", "왼쪽 화살표 키"),
    VirtualKeyInfo(0x26, "UP", "위쪽 화살표 키"),
    VirtualKeyInfo(0x27, "RIGHT", "오른쪽 화살표 키"),
    VirtualKeyInfo(0x28, "DOWN", "아래쪽 화살표 키"),
    VirtualKeyInfo(0x2C, "SNAPSHOT", "Print Screen 키"),
    VirtualKeyInfo(0x2D, "INSERT", "Ins 키"),
    VirtualKeyInfo(0x2E, "DELETE", "DEL 키"),
    VirtualKeyInfo(0x30, "0", "0 키"),
    VirtualKeyInfo(0x31, "1", "1 키"),
    VirtualKeyInfo(0x32, "2", "2 키"),
    VirtualKeyInfo(0x33, "3", "3 키"),
    VirtualKeyInfo(0x34, "4", "4 키"),
    VirtualKeyInfo(0x35, "5", "5 키"),
    VirtualKeyInfo(0x36, "6", "6 키"),
    VirtualKeyInfo(0x37, "7", "7 키"),
    VirtualKeyInfo(0x38, "8", "8 키"),
    VirtualKeyInfo(0x39, "9", "9 키"),
    VirtualKeyInfo(0x41, "A", "A 키"),
    VirtualKeyInfo(0x42, "B", "B 키"),
    VirtualKeyInfo(0x43, "C", "C 키"),
    VirtualKeyInfo(0x44, "D", "D 키"),
    VirtualKeyInfo(0x45, "E", "E 키"),
    VirtualKeyInfo(0x46, "F", "F 키"),
    VirtualKeyInfo(0x47, "G", "G 키"),
    VirtualKeyInfo(0x48, "H", "H 키"),
    VirtualKeyInfo(0x49, "I", "I 키"),
    VirtualKeyInfo(0x4A, "J", "J 키"),
    VirtualKeyInfo(0x4B, "K", "K 키"),
    VirtualKeyInfo(0x4C, "L", "L 키"),
    VirtualKeyInfo(0x4D, "M", "M 키"),
    VirtualKeyInfo(0x4E, "N", "N 키"),
    VirtualKeyInfo(0x4F, "O", "O 키"),
    VirtualKeyInfo(0x50, "P", "P 키"),
    VirtualKeyInfo(0x51, "Q", "Q 키"),
    VirtualKeyInfo(0x52, "R", "R 키"),
    VirtualKeyInfo(0x53, "S", "S 키"),
    VirtualKeyInfo(0x54, "T", "T 키"),
    VirtualKeyInfo(0x55, "U", "U 키"),
    VirtualKeyInfo(0x56, "V", "V 키"),
    VirtualKeyInfo(0x57, "W", "W 키"),
    VirtualKeyInfo(0x58, "X", "X 키"),
    VirtualKeyInfo(0x59, "Y", "Y 키"),
    VirtualKeyInfo(0x5A, "Z", "Z 키"),
    VirtualKeyInfo(0x5B, "LWIN", "왼쪽 Windows 키"),
    VirtualKeyInfo(0x5C, "RWIN", "오른쪽 Windows 키"),
    VirtualKeyInfo(0x60, "NUMPAD0", "숫자 키패드 0 키"),
    VirtualKeyInfo(0x61, "NUMPAD1", "숫자 키패드 1 키"),
    VirtualKeyInfo(0x62, "NUMPAD2", "숫자 키패드 2 키"),
    VirtualKeyInfo(0x63, "NUMPAD3", "숫자 키패드 3 키"),
    VirtualKeyInfo(0x64, "NUMPAD4", "숫자 키패드 4 키"),
    VirtualKeyInfo(0x65, "NUMPAD5", "숫자 키패드 5 키"),
    VirtualKeyInfo(0x66, "NUMPAD6", "숫자 키패드 6 키"),
    VirtualKeyInfo(0x67, "NUMPAD7", "숫자 키패드 7 키"),
    VirtualKeyInfo(0x68, "NUMPAD8", "숫자 키패드 8 키"),
    VirtualKeyInfo(0x69, "NUMPAD9", "숫자 키패드 9 키"),
    VirtualKeyInfo(0x6A, "MULTIPLY", "곱하기 키"),
    VirtualKeyInfo(0x6B, "ADD", "더하기 키"),
    VirtualKeyInfo(0x6C, "SEPARATOR", "구분 기호 키"),
    VirtualKeyInfo(0x6D, "SUBTRACT", "빼기 키"),
    VirtualKeyInfo(0x6E, "DECIMAL", "소수점 키"),
    VirtualKeyInfo(0x6F, "DIVIDE", "나누기 키"),
    VirtualKeyInfo(0x70, "F1", "F1 키"),
    VirtualKeyInfo(0x71, "F2", "F2 키"),
    VirtualKeyInfo(0x72, "F3", "F3 키"),
    VirtualKeyInfo(0x73, "F4", "F4 키"),
    VirtualKeyInfo(0x74, "F5", "F5 키"),
    VirtualKeyInfo(0x75, "F6", "F6 키"),
    VirtualKeyInfo(0x76, "F7", "F7 키"),
    VirtualKeyInfo(0x77, "F8", "F8 키"),
    VirtualKeyInfo(0x78, "F9", "F9 키"),
    VirtualKeyInfo(0x79, "F10", "F10 키"),
    VirtualKeyInfo(0x7A, "F11", "F11 키"),
    VirtualKeyInfo(0x7B, "F12", "F12 키"),
    VirtualKeyInfo(0x90, "NUMLOCK", "Num Lock 키"),
    VirtualKeyInfo(0x91, "SCROLL", "Scroll Lock 키"),
]

# # To print the list of VirtualKeyInfo objects
# for vk in g_vk_list:
#     print(f"{vk.vk_code}: {vk.vk_name} - {vk.vk_desc}")
