# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLayout,
    QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSpacerItem, QStatusBar, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(710, 494)
        font = QFont()
        font.setFamilies([u"Helvetica"])
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color: rgb(234, 238, 238)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        font1 = QFont()
        font1.setBold(False)
        self.centralwidget.setFont(font1)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(150, 75, 550, 392))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QSize(550, 388))
        self.scrollArea.setMaximumSize(QSize(550, 600))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.scrollArea.setFrameShape(QFrame.Shape.Box)
        self.scrollArea.setFrameShadow(QFrame.Shadow.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 590, 540))
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QSize(590, 540))
        self.scrollAreaWidgetContents.setMaximumSize(QSize(590, 540))
        self.Setting_frame = QFrame(self.scrollAreaWidgetContents)
        self.Setting_frame.setObjectName(u"Setting_frame")
        self.Setting_frame.setGeometry(QRect(15, 350, 520, 171))
        self.Setting_frame.setFrameShape(QFrame.Shape.Box)
        self.Setting_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.frame_timeset1 = QFrame(self.Setting_frame)
        self.frame_timeset1.setObjectName(u"frame_timeset1")
        self.frame_timeset1.setGeometry(QRect(5, 10, 510, 50))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_timeset1.sizePolicy().hasHeightForWidth())
        self.frame_timeset1.setSizePolicy(sizePolicy1)
        self.frame_timeset1.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_timeset1.setFrameShadow(QFrame.Shadow.Plain)
        self.label = QLabel(self.frame_timeset1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 131, 31))
        font2 = QFont()
        font2.setFamilies([u"Helvetica"])
        font2.setPointSize(13)
        self.label.setFont(font2)
        self.verticalFrame = QFrame(self.frame_timeset1)
        self.verticalFrame.setObjectName(u"verticalFrame")
        self.verticalFrame.setGeometry(QRect(150, 0, 41, 51))
        self.verticalLayout = QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.Button_minus1 = QPushButton(self.verticalFrame)
        self.Button_minus1.setObjectName(u"Button_minus1")
        sizePolicy1.setHeightForWidth(self.Button_minus1.sizePolicy().hasHeightForWidth())
        self.Button_minus1.setSizePolicy(sizePolicy1)
        self.Button_minus1.setMaximumSize(QSize(30, 20))
        self.Button_minus1.setFont(font2)
        self.Button_minus1.setAutoFillBackground(False)
        self.Button_minus1.setStyleSheet(u"QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #8f8f91;\n"
"    background-color: #f0f0f0;\n"
"    padding: 2px 4px;\n"
"}")
        self.Button_minus1.setFlat(True)

        self.verticalLayout.addWidget(self.Button_minus1)

        self.verticalSpacer_2 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_2)

        self.verticalLayout.setStretch(1, 1)
        self.verticalFrame_4 = QFrame(self.frame_timeset1)
        self.verticalFrame_4.setObjectName(u"verticalFrame_4")
        self.verticalFrame_4.setGeometry(QRect(260, 0, 41, 51))
        self.verticalLayout_4 = QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer_3 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_4.addItem(self.verticalSpacer_3)

        self.Button_plus1 = QPushButton(self.verticalFrame_4)
        self.Button_plus1.setObjectName(u"Button_plus1")
        sizePolicy1.setHeightForWidth(self.Button_plus1.sizePolicy().hasHeightForWidth())
        self.Button_plus1.setSizePolicy(sizePolicy1)
        self.Button_plus1.setMaximumSize(QSize(30, 20))
        font3 = QFont()
        font3.setFamilies([u"Helvetica"])
        font3.setPointSize(13)
        font3.setBold(False)
        font3.setHintingPreference(QFont.PreferVerticalHinting)
        self.Button_plus1.setFont(font3)
        self.Button_plus1.setAutoFillBackground(False)
        self.Button_plus1.setStyleSheet(u"QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #8f8f91;\n"
"    background-color: #f0f0f0;\n"
"    padding: 2px 4px;\n"
"}")
        self.Button_plus1.setFlat(True)

        self.verticalLayout_4.addWidget(self.Button_plus1)

        self.verticalSpacer_4 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_4.addItem(self.verticalSpacer_4)

        self.verticalLayout_4.setStretch(1, 1)
        self.verticalFrame_7 = QFrame(self.frame_timeset1)
        self.verticalFrame_7.setObjectName(u"verticalFrame_7")
        self.verticalFrame_7.setGeometry(QRect(190, 0, 71, 51))
        self.verticalLayout_7 = QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer_9 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_7.addItem(self.verticalSpacer_9)

        self.entry1 = QLineEdit(self.verticalFrame_7)
        self.entry1.setObjectName(u"entry1")
        self.entry1.setFont(font2)
        self.entry1.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_7.addWidget(self.entry1)

        self.verticalSpacer_10 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_7.addItem(self.verticalSpacer_10)

        self.verticalLayout_7.setStretch(1, 1)
        self.frame_timeset2 = QFrame(self.Setting_frame)
        self.frame_timeset2.setObjectName(u"frame_timeset2")
        self.frame_timeset2.setGeometry(QRect(5, 65, 510, 50))
        self.frame_timeset2.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_timeset2.setFrameShadow(QFrame.Shadow.Plain)
        self.label_2 = QLabel(self.frame_timeset2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 131, 31))
        self.label_2.setFont(font2)
        self.verticalFrame_5 = QFrame(self.frame_timeset2)
        self.verticalFrame_5.setObjectName(u"verticalFrame_5")
        self.verticalFrame_5.setGeometry(QRect(260, 0, 41, 51))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.verticalFrame_5.sizePolicy().hasHeightForWidth())
        self.verticalFrame_5.setSizePolicy(sizePolicy2)
        self.verticalLayout_5 = QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer_5 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_5.addItem(self.verticalSpacer_5)

        self.Button_plus2 = QPushButton(self.verticalFrame_5)
        self.Button_plus2.setObjectName(u"Button_plus2")
        sizePolicy1.setHeightForWidth(self.Button_plus2.sizePolicy().hasHeightForWidth())
        self.Button_plus2.setSizePolicy(sizePolicy1)
        self.Button_plus2.setMaximumSize(QSize(30, 20))
        self.Button_plus2.setFont(font3)
        self.Button_plus2.setAutoFillBackground(False)
        self.Button_plus2.setStyleSheet(u"QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #8f8f91;\n"
"    background-color: #f0f0f0;\n"
"    padding: 2px 4px;\n"
"}")
        self.Button_plus2.setFlat(True)

        self.verticalLayout_5.addWidget(self.Button_plus2)

        self.verticalSpacer_6 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_5.addItem(self.verticalSpacer_6)

        self.verticalLayout_5.setStretch(1, 1)
        self.verticalFrame_6 = QFrame(self.frame_timeset2)
        self.verticalFrame_6.setObjectName(u"verticalFrame_6")
        self.verticalFrame_6.setGeometry(QRect(150, 0, 41, 51))
        self.verticalLayout_6 = QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer_7 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_6.addItem(self.verticalSpacer_7)

        self.Button_minus2 = QPushButton(self.verticalFrame_6)
        self.Button_minus2.setObjectName(u"Button_minus2")
        sizePolicy1.setHeightForWidth(self.Button_minus2.sizePolicy().hasHeightForWidth())
        self.Button_minus2.setSizePolicy(sizePolicy1)
        self.Button_minus2.setMaximumSize(QSize(30, 20))
        self.Button_minus2.setFont(font2)
        self.Button_minus2.setAutoFillBackground(False)
        self.Button_minus2.setStyleSheet(u"QPushButton {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #8f8f91;\n"
"    background-color: #f0f0f0;\n"
"    padding: 2px 4px;\n"
"}")
        self.Button_minus2.setFlat(True)

        self.verticalLayout_6.addWidget(self.Button_minus2)

        self.verticalSpacer_8 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_6.addItem(self.verticalSpacer_8)

        self.verticalLayout_6.setStretch(1, 1)
        self.verticalFrame_8 = QFrame(self.frame_timeset2)
        self.verticalFrame_8.setObjectName(u"verticalFrame_8")
        self.verticalFrame_8.setGeometry(QRect(190, 0, 71, 51))
        self.verticalLayout_8 = QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalSpacer_11 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_8.addItem(self.verticalSpacer_11)

        self.enrty2 = QLineEdit(self.verticalFrame_8)
        self.enrty2.setObjectName(u"enrty2")
        self.enrty2.setFont(font2)
        self.enrty2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_8.addWidget(self.enrty2)

        self.verticalSpacer_12 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_8.addItem(self.verticalSpacer_12)

        self.verticalLayout_8.setStretch(1, 1)
        self.frame_timeset3 = QFrame(self.Setting_frame)
        self.frame_timeset3.setObjectName(u"frame_timeset3")
        self.frame_timeset3.setGeometry(QRect(5, 120, 510, 50))
        self.frame_timeset3.setFrameShape(QFrame.Shape.NoFrame)
        self.frame_timeset3.setFrameShadow(QFrame.Shadow.Plain)
        self.label_3 = QLabel(self.frame_timeset3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 10, 91, 31))
        self.label_3.setFont(font2)
        self.frame = QFrame(self.frame_timeset3)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(155, 10, 30, 30))
        self.frame.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.frame.setFrameShape(QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_label6 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label6.setObjectName(u"Image_label6")
        self.Image_label6.setGeometry(QRect(213, 311, 120, 25))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.Image_label6.sizePolicy().hasHeightForWidth())
        self.Image_label6.setSizePolicy(sizePolicy3)
        self.Image_label6.setMinimumSize(QSize(120, 25))
        self.Image_label6.setMaximumSize(QSize(120, 30))
        self.Image_label6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_label1 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label1.setObjectName(u"Image_label1")
        self.Image_label1.setGeometry(QRect(43, 146, 120, 25))
        sizePolicy3.setHeightForWidth(self.Image_label1.sizePolicy().hasHeightForWidth())
        self.Image_label1.setSizePolicy(sizePolicy3)
        self.Image_label1.setMinimumSize(QSize(120, 25))
        self.Image_label1.setMaximumSize(QSize(120, 30))
        self.Image_label1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_frame7 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame7.setObjectName(u"Image_frame7")
        self.Image_frame7.setGeometry(QRect(383, 190, 120, 120))
        sizePolicy3.setHeightForWidth(self.Image_frame7.sizePolicy().hasHeightForWidth())
        self.Image_frame7.setSizePolicy(sizePolicy3)
        self.Image_frame7.setMinimumSize(QSize(120, 120))
        self.Image_frame7.setMaximumSize(QSize(100, 100))
        self.Image_frame7.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame7.setFrameShape(QFrame.Shape.Box)
        self.Image_frame7.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_label7 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label7.setObjectName(u"Image_label7")
        self.Image_label7.setGeometry(QRect(383, 311, 120, 25))
        sizePolicy3.setHeightForWidth(self.Image_label7.sizePolicy().hasHeightForWidth())
        self.Image_label7.setSizePolicy(sizePolicy3)
        self.Image_label7.setMinimumSize(QSize(120, 25))
        self.Image_label7.setMaximumSize(QSize(120, 30))
        self.Image_label7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_label2 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label2.setObjectName(u"Image_label2")
        self.Image_label2.setGeometry(QRect(213, 146, 120, 25))
        sizePolicy3.setHeightForWidth(self.Image_label2.sizePolicy().hasHeightForWidth())
        self.Image_label2.setSizePolicy(sizePolicy3)
        self.Image_label2.setMinimumSize(QSize(120, 25))
        self.Image_label2.setMaximumSize(QSize(120, 30))
        self.Image_label2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_frame2 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame2.setObjectName(u"Image_frame2")
        self.Image_frame2.setGeometry(QRect(213, 25, 120, 120))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(10)
        sizePolicy4.setVerticalStretch(10)
        sizePolicy4.setHeightForWidth(self.Image_frame2.sizePolicy().hasHeightForWidth())
        self.Image_frame2.setSizePolicy(sizePolicy4)
        self.Image_frame2.setMinimumSize(QSize(120, 120))
        self.Image_frame2.setMaximumSize(QSize(100, 100))
        self.Image_frame2.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame2.setFrameShape(QFrame.Shape.Box)
        self.Image_frame2.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_frame6 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame6.setObjectName(u"Image_frame6")
        self.Image_frame6.setGeometry(QRect(213, 190, 120, 120))
        sizePolicy3.setHeightForWidth(self.Image_frame6.sizePolicy().hasHeightForWidth())
        self.Image_frame6.setSizePolicy(sizePolicy3)
        self.Image_frame6.setMinimumSize(QSize(120, 120))
        self.Image_frame6.setMaximumSize(QSize(100, 100))
        self.Image_frame6.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame6.setFrameShape(QFrame.Shape.Box)
        self.Image_frame6.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_label5 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label5.setObjectName(u"Image_label5")
        self.Image_label5.setGeometry(QRect(43, 311, 120, 25))
        sizePolicy3.setHeightForWidth(self.Image_label5.sizePolicy().hasHeightForWidth())
        self.Image_label5.setSizePolicy(sizePolicy3)
        self.Image_label5.setMinimumSize(QSize(120, 25))
        self.Image_label5.setMaximumSize(QSize(120, 30))
        self.Image_label5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_frame1 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame1.setObjectName(u"Image_frame1")
        self.Image_frame1.setEnabled(True)
        self.Image_frame1.setGeometry(QRect(43, 25, 120, 120))
        sizePolicy3.setHeightForWidth(self.Image_frame1.sizePolicy().hasHeightForWidth())
        self.Image_frame1.setSizePolicy(sizePolicy3)
        self.Image_frame1.setMinimumSize(QSize(120, 120))
        self.Image_frame1.setMaximumSize(QSize(100, 100))
        self.Image_frame1.setAutoFillBackground(False)
        self.Image_frame1.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame1.setFrameShape(QFrame.Shape.Box)
        self.Image_frame1.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_frame3 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame3.setObjectName(u"Image_frame3")
        self.Image_frame3.setGeometry(QRect(383, 25, 120, 120))
        sizePolicy3.setHeightForWidth(self.Image_frame3.sizePolicy().hasHeightForWidth())
        self.Image_frame3.setSizePolicy(sizePolicy3)
        self.Image_frame3.setMinimumSize(QSize(120, 120))
        self.Image_frame3.setMaximumSize(QSize(100, 100))
        self.Image_frame3.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame3.setFrameShape(QFrame.Shape.Box)
        self.Image_frame3.setFrameShadow(QFrame.Shadow.Plain)
        self.Image_label3 = QLabel(self.scrollAreaWidgetContents)
        self.Image_label3.setObjectName(u"Image_label3")
        self.Image_label3.setGeometry(QRect(383, 146, 120, 25))
        sizePolicy3.setHeightForWidth(self.Image_label3.sizePolicy().hasHeightForWidth())
        self.Image_label3.setSizePolicy(sizePolicy3)
        self.Image_label3.setMinimumSize(QSize(120, 25))
        self.Image_label3.setMaximumSize(QSize(120, 30))
        self.Image_label3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Image_frame5 = QFrame(self.scrollAreaWidgetContents)
        self.Image_frame5.setObjectName(u"Image_frame5")
        self.Image_frame5.setGeometry(QRect(43, 190, 120, 120))
        sizePolicy3.setHeightForWidth(self.Image_frame5.sizePolicy().hasHeightForWidth())
        self.Image_frame5.setSizePolicy(sizePolicy3)
        self.Image_frame5.setMinimumSize(QSize(120, 120))
        self.Image_frame5.setMaximumSize(QSize(100, 100))
        self.Image_frame5.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Image_frame5.setFrameShape(QFrame.Shape.Box)
        self.Image_frame5.setFrameShadow(QFrame.Shadow.Plain)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Title_frame = QFrame(self.centralwidget)
        self.Title_frame.setObjectName(u"Title_frame")
        self.Title_frame.setGeometry(QRect(150, 10, 550, 66))
        self.Title_frame.setMinimumSize(QSize(550, 66))
        self.Title_frame.setMaximumSize(QSize(550, 66))
        self.Title_frame.setFont(font)
        self.Title_frame.setStyleSheet(u"background:rgb(206, 208, 208)")
        self.Title_frame.setFrameShape(QFrame.Shape.Box)
        self.Title_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.Title_label = QLabel(self.Title_frame)
        self.Title_label.setObjectName(u"Title_label")
        self.Title_label.setGeometry(QRect(1, 1, 548, 64))
        sizePolicy2.setHeightForWidth(self.Title_label.sizePolicy().hasHeightForWidth())
        self.Title_label.setSizePolicy(sizePolicy2)
        font4 = QFont()
        font4.setFamilies([u"Helvetica"])
        font4.setPointSize(30)
        font4.setBold(False)
        self.Title_label.setFont(font4)
        self.Title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Menu_frame = QFrame(self.centralwidget)
        self.Menu_frame.setObjectName(u"Menu_frame")
        self.Menu_frame.setGeometry(QRect(10, 10, 130, 457))
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.Menu_frame.sizePolicy().hasHeightForWidth())
        self.Menu_frame.setSizePolicy(sizePolicy5)
        self.Menu_frame.setMinimumSize(QSize(130, 457))
        self.Menu_frame.setMaximumSize(QSize(130, 457))
        self.Menu_frame.setFont(font)
        self.Menu_frame.setAutoFillBackground(False)
        self.Menu_frame.setStyleSheet(u"background-color: rgb(234, 238, 238);\n"
"")
        self.Menu_frame.setFrameShape(QFrame.Shape.Box)
        self.Menu_frame.setLineWidth(1)
        self.MenuLabel2 = QLabel(self.Menu_frame)
        self.MenuLabel2.setObjectName(u"MenuLabel2")
        self.MenuLabel2.setGeometry(QRect(1, 66, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel2.sizePolicy().hasHeightForWidth())
        self.MenuLabel2.setSizePolicy(sizePolicy2)
        self.MenuLabel2.setMinimumSize(QSize(128, 65))
        self.MenuLabel2.setMaximumSize(QSize(128, 65))
        self.MenuLabel2.setFont(font2)
        self.MenuLabel2.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.MenuLabel2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel6 = QLabel(self.Menu_frame)
        self.MenuLabel6.setObjectName(u"MenuLabel6")
        self.MenuLabel6.setGeometry(QRect(1, 326, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel6.sizePolicy().hasHeightForWidth())
        self.MenuLabel6.setSizePolicy(sizePolicy2)
        self.MenuLabel6.setMinimumSize(QSize(128, 65))
        self.MenuLabel6.setMaximumSize(QSize(128, 65))
        self.MenuLabel6.setFont(font2)
        self.MenuLabel6.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.MenuLabel6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel4 = QLabel(self.Menu_frame)
        self.MenuLabel4.setObjectName(u"MenuLabel4")
        self.MenuLabel4.setGeometry(QRect(1, 196, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel4.sizePolicy().hasHeightForWidth())
        self.MenuLabel4.setSizePolicy(sizePolicy2)
        self.MenuLabel4.setMinimumSize(QSize(128, 65))
        self.MenuLabel4.setMaximumSize(QSize(128, 65))
        self.MenuLabel4.setFont(font2)
        self.MenuLabel4.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.MenuLabel4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel5 = QLabel(self.Menu_frame)
        self.MenuLabel5.setObjectName(u"MenuLabel5")
        self.MenuLabel5.setGeometry(QRect(1, 261, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel5.sizePolicy().hasHeightForWidth())
        self.MenuLabel5.setSizePolicy(sizePolicy2)
        self.MenuLabel5.setMinimumSize(QSize(128, 65))
        self.MenuLabel5.setMaximumSize(QSize(128, 65))
        self.MenuLabel5.setFont(font2)
        self.MenuLabel5.setStyleSheet(u"background-color: rgb(148, 55, 255);\n"
"color:rgb(255, 255, 255);")
        self.MenuLabel5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel7 = QLabel(self.Menu_frame)
        self.MenuLabel7.setObjectName(u"MenuLabel7")
        self.MenuLabel7.setGeometry(QRect(1, 391, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel7.sizePolicy().hasHeightForWidth())
        self.MenuLabel7.setSizePolicy(sizePolicy2)
        self.MenuLabel7.setMinimumSize(QSize(128, 65))
        self.MenuLabel7.setMaximumSize(QSize(128, 65))
        self.MenuLabel7.setFont(font2)
        self.MenuLabel7.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.MenuLabel7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel1 = QLabel(self.Menu_frame)
        self.MenuLabel1.setObjectName(u"MenuLabel1")
        self.MenuLabel1.setGeometry(QRect(1, 1, 128, 65))
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(128)
        sizePolicy6.setVerticalStretch(60)
        sizePolicy6.setHeightForWidth(self.MenuLabel1.sizePolicy().hasHeightForWidth())
        self.MenuLabel1.setSizePolicy(sizePolicy6)
        self.MenuLabel1.setMinimumSize(QSize(128, 65))
        self.MenuLabel1.setMaximumSize(QSize(128, 65))
        self.MenuLabel1.setBaseSize(QSize(0, 0))
        self.MenuLabel1.setFont(font2)
        self.MenuLabel1.setStyleSheet(u"background-color: rgb(148, 55, 255);\n"
"color:rgb(255, 255, 255);")
        self.MenuLabel1.setLineWidth(0)
        self.MenuLabel1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel3 = QLabel(self.Menu_frame)
        self.MenuLabel3.setObjectName(u"MenuLabel3")
        self.MenuLabel3.setGeometry(QRect(1, 131, 128, 65))
        sizePolicy2.setHeightForWidth(self.MenuLabel3.sizePolicy().hasHeightForWidth())
        self.MenuLabel3.setSizePolicy(sizePolicy2)
        self.MenuLabel3.setMinimumSize(QSize(128, 65))
        self.MenuLabel3.setMaximumSize(QSize(128, 65))
        self.MenuLabel3.setFont(font2)
        self.MenuLabel3.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.MenuLabel3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel1.raise_()
        self.MenuLabel2.raise_()
        self.MenuLabel6.raise_()
        self.MenuLabel4.raise_()
        self.MenuLabel5.raise_()
        self.MenuLabel7.raise_()
        self.MenuLabel3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\ubc30\ub2ec \uae30\ubcf8 \uc811\uc218\uc2dc\uac04(\ubd84)", None))
        self.Button_minus1.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.Button_plus1.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.entry1.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\ud3ec\uc7a5 \uae30\ubcf8 \uc811\uc218\uc2dc\uac04(\ubd84)", None))
        self.Button_plus2.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.Button_minus2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.enrty2.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ub9e4\ud06c\ub85c \ub3d9\uc791 \uc124\uc815", None))
        self.Image_label6.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 6", None))
        self.Image_label1.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 1", None))
        self.Image_label7.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 7", None))
        self.Image_label2.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 2", None))
        self.Image_label5.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 5", None))
        self.Image_label3.setText(QCoreApplication.translate("MainWindow", u"\uc774\ubbf8\uc9c0 3", None))
        self.Title_label.setText(QCoreApplication.translate("MainWindow", u"Menu Name", None))
        self.MenuLabel2.setText(QCoreApplication.translate("MainWindow", u"Menu2", None))
        self.MenuLabel6.setText(QCoreApplication.translate("MainWindow", u"Menu6", None))
        self.MenuLabel4.setText(QCoreApplication.translate("MainWindow", u"Menu4", None))
        self.MenuLabel5.setText(QCoreApplication.translate("MainWindow", u"Menu5", None))
        self.MenuLabel7.setText(QCoreApplication.translate("MainWindow", u"Menu7", None))
        self.MenuLabel1.setText(QCoreApplication.translate("MainWindow", u"Menu1", None))
        self.MenuLabel3.setText(QCoreApplication.translate("MainWindow", u"Menu3", None))
    # retranslateUi

